version: '3.8'

services:
  # Servicio para el Monolito MVC (PHP puro)
  mvc-app:
    image: php:8.2-apache
    container_name: mvc_catalogo_php
    ports:
      - "8080:80"
    volumes:
      - ./mvc-catalogo:/var/www/html
    restart: unless-stopped

  # Servicio para la SPA (React + Vite)
  spa-app:
    image: node:20-alpine
    container_name: spa_catalogo_react
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./spa-catalogo:/app
    # Instala dependencias y levanta el servidor exponiendo a la red de Docker
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    restart: unless-stopped